name: CI-Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ 8, 11, 17, 19 ] # LTS versions + latest version
    name: "Run tests with JDK ${{ matrix.java }}"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: ${{ matrix.java }}
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.3
          arguments: test